export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_FAILURE = 'FETCH_PHONES_FAILURE';

export const SEARCH_PHONE = 'SEARCH_PHONE';


export const ADD_PHONE_TO_BASKET = 'ADD_PHONE_TO_BASKET';
export const REMOVE_PHONE_FROM_BASKET = 'REMOVE_PHONE_FROM_BASKET';
export const CLEAN_BASKET = 'CLEAN_BASKET';

export const SET_QUERY = 'SET_QUERY';
export const SET_FILTER = 'SET_FILTER';

export const SET_PHONES = 'SET_PHONES';
export const SET_IS_READY = 'SET_IS_READY';


export const SORT_GOODS_BY_NAME = 'SORT_GOODS_BY_NAME';
export const SORT_GOODS_BY_PRICE = 'SORT_GOODS_BY_PRICE';




